System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "typescript",
  typescriptOptions: {
    "emitDecoratorMetadata": true
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "jspmdevbundle.js": [
      "npm:typescript@2.5.3.js",
      "npm:typescript@2.5.3/lib/typescript.js",
      "npm:source-map-support@0.5.0.js",
      "npm:source-map-support@0.5.0/source-map-support.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.10.js",
      "npm:process@0.11.10/browser.js",
      "github:jspm/nodelibs-buffer@0.1.1.js",
      "github:jspm/nodelibs-buffer@0.1.1/index.js",
      "npm:buffer@5.0.8.js",
      "npm:buffer@5.0.8/index.js",
      "npm:ieee754@1.1.8.js",
      "npm:ieee754@1.1.8/index.js",
      "npm:base64-js@1.2.1.js",
      "npm:base64-js@1.2.1/index.js",
      "github:jspm/nodelibs-module@0.1.0.js",
      "github:jspm/nodelibs-module@0.1.0/index.js",
      "github:jspm/nodelibs-fs@0.1.2.js",
      "github:jspm/nodelibs-fs@0.1.2/index.js",
      "github:jspm/nodelibs-path@0.1.0.js",
      "github:jspm/nodelibs-path@0.1.0/index.js",
      "npm:path-browserify@0.0.0.js",
      "npm:path-browserify@0.0.0/index.js",
      "npm:source-map@0.6.1.js",
      "npm:source-map@0.6.1/source-map.js",
      "npm:source-map@0.6.1/lib/source-node.js",
      "npm:source-map@0.6.1/lib/util.js",
      "npm:source-map@0.6.1/lib/source-map-generator.js",
      "npm:source-map@0.6.1/lib/mapping-list.js",
      "npm:source-map@0.6.1/lib/array-set.js",
      "npm:source-map@0.6.1/lib/base64-vlq.js",
      "npm:source-map@0.6.1/lib/base64.js",
      "npm:source-map@0.6.1/lib/source-map-consumer.js",
      "npm:source-map@0.6.1/lib/quick-sort.js",
      "npm:source-map@0.6.1/lib/binary-search.js",
      "github:jspm/nodelibs-crypto@0.1.0.js",
      "github:jspm/nodelibs-crypto@0.1.0/index.js",
      "npm:crypto-browserify@3.11.1.js",
      "npm:crypto-browserify@3.11.1/index.js",
      "npm:public-encrypt@4.0.0.js",
      "npm:public-encrypt@4.0.0/browser.js",
      "npm:public-encrypt@4.0.0/privateDecrypt.js",
      "npm:public-encrypt@4.0.0/withPublic.js",
      "npm:bn.js@4.11.8.js",
      "npm:bn.js@4.11.8/lib/bn.js",
      "npm:create-hash@1.1.3.js",
      "npm:create-hash@1.1.3/browser.js",
      "npm:cipher-base@1.0.4.js",
      "npm:cipher-base@1.0.4/index.js",
      "npm:inherits@2.0.3.js",
      "npm:inherits@2.0.3/inherits_browser.js",
      "github:jspm/nodelibs-string_decoder@0.1.0.js",
      "github:jspm/nodelibs-string_decoder@0.1.0/index.js",
      "npm:string_decoder@0.10.31.js",
      "npm:string_decoder@0.10.31/index.js",
      "github:jspm/nodelibs-stream@0.1.0.js",
      "github:jspm/nodelibs-stream@0.1.0/index.js",
      "npm:stream-browserify@1.0.0.js",
      "npm:stream-browserify@1.0.0/index.js",
      "npm:readable-stream@1.1.14/passthrough.js",
      "npm:readable-stream@1.1.14/lib/_stream_passthrough.js",
      "npm:core-util-is@1.0.2.js",
      "npm:core-util-is@1.0.2/lib/util.js",
      "npm:readable-stream@1.1.14/lib/_stream_transform.js",
      "npm:readable-stream@1.1.14/lib/_stream_duplex.js",
      "npm:readable-stream@1.1.14/lib/_stream_writable.js",
      "npm:readable-stream@1.1.14/lib/_stream_readable.js",
      "github:jspm/nodelibs-events@0.1.1.js",
      "github:jspm/nodelibs-events@0.1.1/index.js",
      "npm:events@1.0.2.js",
      "npm:events@1.0.2/events.js",
      "npm:isarray@0.0.1.js",
      "npm:isarray@0.0.1/index.js",
      "npm:readable-stream@1.1.14/transform.js",
      "npm:readable-stream@1.1.14/duplex.js",
      "npm:readable-stream@1.1.14/writable.js",
      "npm:readable-stream@1.1.14/readable.js",
      "npm:safe-buffer@5.1.1.js",
      "npm:safe-buffer@5.1.1/index.js",
      "npm:sha.js@2.4.9.js",
      "npm:sha.js@2.4.9/index.js",
      "npm:sha.js@2.4.9/sha512.js",
      "npm:sha.js@2.4.9/hash.js",
      "npm:sha.js@2.4.9/sha384.js",
      "npm:sha.js@2.4.9/sha256.js",
      "npm:sha.js@2.4.9/sha224.js",
      "npm:sha.js@2.4.9/sha1.js",
      "npm:sha.js@2.4.9/sha.js",
      "npm:ripemd160@2.0.1.js",
      "npm:ripemd160@2.0.1/index.js",
      "npm:hash-base@2.0.2.js",
      "npm:hash-base@2.0.2/index.js",
      "npm:create-hash@1.1.3/md5.js",
      "npm:create-hash@1.1.3/make-hash.js",
      "npm:browserify-rsa@4.0.1.js",
      "npm:browserify-rsa@4.0.1/index.js",
      "npm:randombytes@2.0.5.js",
      "npm:randombytes@2.0.5/browser.js",
      "npm:public-encrypt@4.0.0/xor.js",
      "npm:public-encrypt@4.0.0/mgf.js",
      "npm:parse-asn1@5.1.0.js",
      "npm:parse-asn1@5.1.0/index.js",
      "npm:pbkdf2@3.0.14.js",
      "npm:pbkdf2@3.0.14/browser.js",
      "npm:pbkdf2@3.0.14/lib/sync-browser.js",
      "npm:pbkdf2@3.0.14/lib/default-encoding.js",
      "npm:pbkdf2@3.0.14/lib/precondition.js",
      "npm:pbkdf2@3.0.14/lib/async.js",
      "npm:browserify-aes@1.0.8.js",
      "npm:browserify-aes@1.0.8/browser.js",
      "npm:browserify-aes@1.0.8/modes/list.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-aes@1.0.8/decrypter.js",
      "npm:evp_bytestokey@1.0.3.js",
      "npm:evp_bytestokey@1.0.3/index.js",
      "npm:md5.js@1.3.4.js",
      "npm:md5.js@1.3.4/index.js",
      "npm:hash-base@3.0.4.js",
      "npm:hash-base@3.0.4/index.js",
      "npm:browserify-aes@1.0.8/aes.js",
      "npm:browserify-aes@1.0.8/streamCipher.js",
      "npm:browserify-aes@1.0.8/modes/index.js",
      "npm:browserify-aes@1.0.8/modes/ctr.js",
      "npm:buffer-xor@1.0.3.js",
      "npm:buffer-xor@1.0.3/index.js",
      "npm:browserify-aes@1.0.8/modes/ofb.js",
      "npm:browserify-aes@1.0.8/modes/cfb1.js",
      "npm:browserify-aes@1.0.8/modes/cfb8.js",
      "npm:browserify-aes@1.0.8/modes/cfb.js",
      "npm:browserify-aes@1.0.8/modes/cbc.js",
      "npm:browserify-aes@1.0.8/modes/ecb.js",
      "npm:browserify-aes@1.0.8/authCipher.js",
      "npm:browserify-aes@1.0.8/ghash.js",
      "npm:browserify-aes@1.0.8/encrypter.js",
      "npm:parse-asn1@5.1.0/fixProc.js",
      "npm:parse-asn1@5.1.0/aesid.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:parse-asn1@5.1.0/asn1.js",
      "npm:parse-asn1@5.1.0/certificate.js",
      "npm:asn1.js@4.9.1.js",
      "npm:asn1.js@4.9.1/lib/asn1.js",
      "npm:asn1.js@4.9.1/lib/asn1/encoders/index.js",
      "npm:asn1.js@4.9.1/lib/asn1/encoders/pem.js",
      "npm:asn1.js@4.9.1/lib/asn1/encoders/der.js",
      "npm:asn1.js@4.9.1/lib/asn1/decoders/index.js",
      "npm:asn1.js@4.9.1/lib/asn1/decoders/pem.js",
      "npm:asn1.js@4.9.1/lib/asn1/decoders/der.js",
      "npm:asn1.js@4.9.1/lib/asn1/constants/index.js",
      "npm:asn1.js@4.9.1/lib/asn1/constants/der.js",
      "npm:asn1.js@4.9.1/lib/asn1/base/index.js",
      "npm:asn1.js@4.9.1/lib/asn1/base/node.js",
      "npm:minimalistic-assert@1.0.0.js",
      "npm:minimalistic-assert@1.0.0/index.js",
      "npm:asn1.js@4.9.1/lib/asn1/base/buffer.js",
      "npm:asn1.js@4.9.1/lib/asn1/base/reporter.js",
      "npm:asn1.js@4.9.1/lib/asn1/api.js",
      "github:jspm/nodelibs-vm@0.1.0.js",
      "github:jspm/nodelibs-vm@0.1.0/index.js",
      "npm:vm-browserify@0.0.4.js",
      "npm:vm-browserify@0.0.4/index.js",
      "npm:indexof@0.0.1.js",
      "npm:indexof@0.0.1/index.js",
      "npm:public-encrypt@4.0.0/publicEncrypt.js",
      "npm:create-ecdh@4.0.0.js",
      "npm:create-ecdh@4.0.0/browser.js",
      "npm:elliptic@6.4.0.js",
      "npm:elliptic@6.4.0/lib/elliptic.js",
      "npm:elliptic@6.4.0/lib/elliptic/eddsa/index.js",
      "npm:elliptic@6.4.0/lib/elliptic/eddsa/signature.js",
      "npm:elliptic@6.4.0/lib/elliptic/eddsa/key.js",
      "npm:hash.js@1.1.3.js",
      "npm:hash.js@1.1.3/lib/hash.js",
      "npm:hash.js@1.1.3/lib/hash/hmac.js",
      "npm:hash.js@1.1.3/lib/hash/utils.js",
      "npm:hash.js@1.1.3/lib/hash/ripemd.js",
      "npm:hash.js@1.1.3/lib/hash/common.js",
      "npm:hash.js@1.1.3/lib/hash/sha.js",
      "npm:hash.js@1.1.3/lib/hash/sha/512.js",
      "npm:hash.js@1.1.3/lib/hash/sha/384.js",
      "npm:hash.js@1.1.3/lib/hash/sha/256.js",
      "npm:hash.js@1.1.3/lib/hash/sha/common.js",
      "npm:hash.js@1.1.3/lib/hash/sha/224.js",
      "npm:hash.js@1.1.3/lib/hash/sha/1.js",
      "npm:elliptic@6.4.0/lib/elliptic/ec/index.js",
      "npm:elliptic@6.4.0/lib/elliptic/ec/signature.js",
      "npm:elliptic@6.4.0/lib/elliptic/ec/key.js",
      "npm:hmac-drbg@1.0.1.js",
      "npm:hmac-drbg@1.0.1/lib/hmac-drbg.js",
      "npm:minimalistic-crypto-utils@1.0.1.js",
      "npm:minimalistic-crypto-utils@1.0.1/lib/utils.js",
      "npm:elliptic@6.4.0/lib/elliptic/curves.js",
      "npm:elliptic@6.4.0/lib/elliptic/precomputed/secp256k1.js",
      "npm:elliptic@6.4.0/lib/elliptic/curve/index.js",
      "npm:elliptic@6.4.0/lib/elliptic/curve/edwards.js",
      "npm:elliptic@6.4.0/lib/elliptic/curve/mont.js",
      "npm:elliptic@6.4.0/lib/elliptic/curve/short.js",
      "npm:elliptic@6.4.0/lib/elliptic/curve/base.js",
      "npm:brorand@1.1.0.js",
      "npm:brorand@1.1.0/index.js",
      "npm:elliptic@6.4.0/lib/elliptic/utils.js",
      "npm:elliptic@6.4.0/package.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-sign@4.0.4.js",
      "npm:browserify-sign@4.0.4/browser/index.js",
      "npm:browserify-sign@4.0.4/browser/algorithms.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-sign@4.0.4/browser/verify.js",
      "npm:browserify-sign@4.0.4/browser/curves.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-sign@4.0.4/browser/sign.js",
      "npm:create-hmac@1.1.6.js",
      "npm:create-hmac@1.1.6/browser.js",
      "npm:create-hmac@1.1.6/legacy.js",
      "npm:diffie-hellman@5.0.2.js",
      "npm:diffie-hellman@5.0.2/browser.js",
      "npm:diffie-hellman@5.0.2/lib/dh.js",
      "npm:diffie-hellman@5.0.2/lib/generatePrime.js",
      "npm:miller-rabin@4.0.1.js",
      "npm:miller-rabin@4.0.1/lib/mr.js",
      "npm:diffie-hellman@5.0.2/lib/primes.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-cipher@1.0.0.js",
      "npm:browserify-cipher@1.0.0/browser.js",
      "npm:browserify-aes@1.0.8/modes.js",
      "npm:browserify-des@1.0.0/modes.js",
      "npm:browserify-des@1.0.0.js",
      "npm:browserify-des@1.0.0/index.js",
      "npm:des.js@1.0.0.js",
      "npm:des.js@1.0.0/lib/des.js",
      "npm:des.js@1.0.0/lib/des/ede.js",
      "npm:des.js@1.0.0/lib/des/cbc.js",
      "npm:des.js@1.0.0/lib/des/des.js",
      "npm:des.js@1.0.0/lib/des/cipher.js",
      "npm:des.js@1.0.0/lib/des/utils.js",
      "npm:browserify-sign@4.0.4/algos.js",
      "github:jspm/nodelibs-os@0.1.0.js",
      "github:jspm/nodelibs-os@0.1.0/index.js",
      "npm:os-browserify@0.1.2.js",
      "npm:os-browserify@0.1.2/browser.js",
      "npm:rxjs@5.5.0.js",
      "npm:rxjs@5.5.0/Rx.js",
      "npm:rxjs@5.5.0/operators/index.js",
      "npm:rxjs@5.5.0/operators/zipAll.js",
      "npm:rxjs@5.5.0/operators/zip.js",
      "npm:rxjs@5.5.0/symbol/iterator.js",
      "npm:rxjs@5.5.0/util/root.js",
      "npm:rxjs@5.5.0/util/subscribeToResult.js",
      "npm:rxjs@5.5.0/symbol/observable.js",
      "npm:rxjs@5.5.0/InnerSubscriber.js",
      "npm:rxjs@5.5.0/Subscriber.js",
      "npm:rxjs@5.5.0/symbol/rxSubscriber.js",
      "npm:rxjs@5.5.0/Observer.js",
      "npm:rxjs@5.5.0/Subscription.js",
      "npm:rxjs@5.5.0/util/UnsubscriptionError.js",
      "npm:rxjs@5.5.0/util/errorObject.js",
      "npm:rxjs@5.5.0/util/tryCatch.js",
      "npm:rxjs@5.5.0/util/isFunction.js",
      "npm:rxjs@5.5.0/util/isObject.js",
      "npm:rxjs@5.5.0/util/isArray.js",
      "npm:rxjs@5.5.0/Observable.js",
      "npm:rxjs@5.5.0/util/pipe.js",
      "npm:rxjs@5.5.0/util/noop.js",
      "npm:rxjs@5.5.0/util/toSubscriber.js",
      "npm:rxjs@5.5.0/util/isPromise.js",
      "npm:rxjs@5.5.0/util/isArrayLike.js",
      "npm:rxjs@5.5.0/OuterSubscriber.js",
      "npm:rxjs@5.5.0/observable/ArrayObservable.js",
      "npm:rxjs@5.5.0/util/isScheduler.js",
      "npm:rxjs@5.5.0/observable/EmptyObservable.js",
      "npm:rxjs@5.5.0/observable/ScalarObservable.js",
      "npm:rxjs@5.5.0/operators/withLatestFrom.js",
      "npm:rxjs@5.5.0/operators/windowWhen.js",
      "npm:rxjs@5.5.0/Subject.js",
      "npm:rxjs@5.5.0/SubjectSubscription.js",
      "npm:rxjs@5.5.0/util/ObjectUnsubscribedError.js",
      "npm:rxjs@5.5.0/operators/windowToggle.js",
      "npm:rxjs@5.5.0/operators/windowTime.js",
      "npm:rxjs@5.5.0/util/isNumeric.js",
      "npm:rxjs@5.5.0/scheduler/async.js",
      "npm:rxjs@5.5.0/scheduler/AsyncScheduler.js",
      "npm:rxjs@5.5.0/Scheduler.js",
      "npm:rxjs@5.5.0/scheduler/AsyncAction.js",
      "npm:rxjs@5.5.0/scheduler/Action.js",
      "npm:rxjs@5.5.0/operators/windowCount.js",
      "npm:rxjs@5.5.0/operators/window.js",
      "npm:rxjs@5.5.0/operators/toArray.js",
      "npm:rxjs@5.5.0/operators/reduce.js",
      "npm:rxjs@5.5.0/operators/defaultIfEmpty.js",
      "npm:rxjs@5.5.0/operators/takeLast.js",
      "npm:rxjs@5.5.0/util/ArgumentOutOfRangeError.js",
      "npm:rxjs@5.5.0/operators/scan.js",
      "npm:rxjs@5.5.0/operators/timestamp.js",
      "npm:rxjs@5.5.0/operators/map.js",
      "npm:rxjs@5.5.0/operators/timeoutWith.js",
      "npm:rxjs@5.5.0/util/isDate.js",
      "npm:rxjs@5.5.0/operators/timeout.js",
      "npm:rxjs@5.5.0/util/TimeoutError.js",
      "npm:rxjs@5.5.0/operators/timeInterval.js",
      "npm:rxjs@5.5.0/operators/throttleTime.js",
      "npm:rxjs@5.5.0/operators/throttle.js",
      "npm:rxjs@5.5.0/operators/tap.js",
      "npm:rxjs@5.5.0/operators/takeWhile.js",
      "npm:rxjs@5.5.0/operators/takeUntil.js",
      "npm:rxjs@5.5.0/operators/take.js",
      "npm:rxjs@5.5.0/operators/switchMapTo.js",
      "npm:rxjs@5.5.0/operators/switchMap.js",
      "npm:rxjs@5.5.0/operators/switchAll.js",
      "npm:rxjs@5.5.0/util/identity.js",
      "npm:rxjs@5.5.0/operators/startWith.js",
      "npm:rxjs@5.5.0/observable/concat.js",
      "npm:rxjs@5.5.0/operators/concatAll.js",
      "npm:rxjs@5.5.0/operators/mergeAll.js",
      "npm:rxjs@5.5.0/operators/mergeMap.js",
      "npm:rxjs@5.5.0/observable/from.js",
      "npm:rxjs@5.5.0/observable/FromObservable.js",
      "npm:rxjs@5.5.0/operators/observeOn.js",
      "npm:rxjs@5.5.0/Notification.js",
      "npm:rxjs@5.5.0/observable/ArrayLikeObservable.js",
      "npm:rxjs@5.5.0/observable/IteratorObservable.js",
      "npm:rxjs@5.5.0/observable/PromiseObservable.js",
      "npm:rxjs@5.5.0/observable/of.js",
      "npm:rxjs@5.5.0/operators/skipWhile.js",
      "npm:rxjs@5.5.0/operators/skipUntil.js",
      "npm:rxjs@5.5.0/operators/skipLast.js",
      "npm:rxjs@5.5.0/operators/skip.js",
      "npm:rxjs@5.5.0/operators/single.js",
      "npm:rxjs@5.5.0/util/EmptyError.js",
      "npm:rxjs@5.5.0/operators/shareReplay.js",
      "npm:rxjs@5.5.0/ReplaySubject.js",
      "npm:rxjs@5.5.0/scheduler/queue.js",
      "npm:rxjs@5.5.0/scheduler/QueueScheduler.js",
      "npm:rxjs@5.5.0/scheduler/QueueAction.js",
      "npm:rxjs@5.5.0/operators/share.js",
      "npm:rxjs@5.5.0/operators/refCount.js",
      "npm:rxjs@5.5.0/operators/multicast.js",
      "npm:rxjs@5.5.0/observable/ConnectableObservable.js",
      "npm:rxjs@5.5.0/operators/sequenceEqual.js",
      "npm:rxjs@5.5.0/operators/sampleTime.js",
      "npm:rxjs@5.5.0/operators/sample.js",
      "npm:rxjs@5.5.0/operators/retryWhen.js",
      "npm:rxjs@5.5.0/operators/retry.js",
      "npm:rxjs@5.5.0/operators/repeatWhen.js",
      "npm:rxjs@5.5.0/operators/repeat.js",
      "npm:rxjs@5.5.0/operators/race.js",
      "npm:rxjs@5.5.0/observable/race.js",
      "npm:rxjs@5.5.0/operators/publishReplay.js",
      "npm:rxjs@5.5.0/operators/publishLast.js",
      "npm:rxjs@5.5.0/AsyncSubject.js",
      "npm:rxjs@5.5.0/operators/publishBehavior.js",
      "npm:rxjs@5.5.0/BehaviorSubject.js",
      "npm:rxjs@5.5.0/operators/publish.js",
      "npm:rxjs@5.5.0/operators/pluck.js",
      "npm:rxjs@5.5.0/operators/partition.js",
      "npm:rxjs@5.5.0/operators/filter.js",
      "npm:rxjs@5.5.0/util/not.js",
      "npm:rxjs@5.5.0/operators/pairwise.js",
      "npm:rxjs@5.5.0/operators/onErrorResumeNext.js",
      "npm:rxjs@5.5.0/operators/min.js",
      "npm:rxjs@5.5.0/operators/mergeScan.js",
      "npm:rxjs@5.5.0/operators/mergeMapTo.js",
      "npm:rxjs@5.5.0/operators/merge.js",
      "npm:rxjs@5.5.0/operators/max.js",
      "npm:rxjs@5.5.0/operators/materialize.js",
      "npm:rxjs@5.5.0/operators/mapTo.js",
      "npm:rxjs@5.5.0/operators/last.js",
      "npm:rxjs@5.5.0/operators/isEmpty.js",
      "npm:rxjs@5.5.0/operators/ignoreElements.js",
      "npm:rxjs@5.5.0/operators/groupBy.js",
      "npm:rxjs@5.5.0/util/FastMap.js",
      "npm:rxjs@5.5.0/util/Map.js",
      "npm:rxjs@5.5.0/util/MapPolyfill.js",
      "npm:rxjs@5.5.0/operators/first.js",
      "npm:rxjs@5.5.0/operators/findIndex.js",
      "npm:rxjs@5.5.0/operators/find.js",
      "npm:rxjs@5.5.0/operators/finalize.js",
      "npm:rxjs@5.5.0/operators/expand.js",
      "npm:rxjs@5.5.0/operators/exhaustMap.js",
      "npm:rxjs@5.5.0/operators/exhaust.js",
      "npm:rxjs@5.5.0/operators/every.js",
      "npm:rxjs@5.5.0/operators/elementAt.js",
      "npm:rxjs@5.5.0/operators/distinctUntilKeyChanged.js",
      "npm:rxjs@5.5.0/operators/distinctUntilChanged.js",
      "npm:rxjs@5.5.0/operators/distinct.js",
      "npm:rxjs@5.5.0/util/Set.js",
      "npm:rxjs@5.5.0/operators/dematerialize.js",
      "npm:rxjs@5.5.0/operators/delayWhen.js",
      "npm:rxjs@5.5.0/operators/delay.js",
      "npm:rxjs@5.5.0/operators/debounceTime.js",
      "npm:rxjs@5.5.0/operators/debounce.js",
      "npm:rxjs@5.5.0/operators/count.js",
      "npm:rxjs@5.5.0/operators/concatMapTo.js",
      "npm:rxjs@5.5.0/operators/concatMap.js",
      "npm:rxjs@5.5.0/operators/concat.js",
      "npm:rxjs@5.5.0/operators/combineLatest.js",
      "npm:rxjs@5.5.0/operators/combineAll.js",
      "npm:rxjs@5.5.0/operators/catchError.js",
      "npm:rxjs@5.5.0/operators/bufferWhen.js",
      "npm:rxjs@5.5.0/operators/bufferToggle.js",
      "npm:rxjs@5.5.0/operators/bufferTime.js",
      "npm:rxjs@5.5.0/operators/bufferCount.js",
      "npm:rxjs@5.5.0/operators/buffer.js",
      "npm:rxjs@5.5.0/operators/auditTime.js",
      "npm:rxjs@5.5.0/observable/timer.js",
      "npm:rxjs@5.5.0/observable/TimerObservable.js",
      "npm:rxjs@5.5.0/operators/audit.js",
      "npm:rxjs@5.5.0/scheduler/animationFrame.js",
      "npm:rxjs@5.5.0/scheduler/AnimationFrameScheduler.js",
      "npm:rxjs@5.5.0/scheduler/AnimationFrameAction.js",
      "npm:rxjs@5.5.0/util/AnimationFrame.js",
      "npm:rxjs@5.5.0/scheduler/asap.js",
      "npm:rxjs@5.5.0/scheduler/AsapScheduler.js",
      "npm:rxjs@5.5.0/scheduler/AsapAction.js",
      "npm:rxjs@5.5.0/util/Immediate.js",
      "npm:rxjs@5.5.0/observable/dom/AjaxObservable.js",
      "npm:rxjs@5.5.0/scheduler/VirtualTimeScheduler.js",
      "npm:rxjs@5.5.0/testing/TestScheduler.js",
      "npm:rxjs@5.5.0/testing/SubscriptionLog.js",
      "npm:rxjs@5.5.0/testing/HotObservable.js",
      "npm:rxjs@5.5.0/util/applyMixins.js",
      "npm:rxjs@5.5.0/testing/SubscriptionLoggable.js",
      "npm:rxjs@5.5.0/testing/ColdObservable.js",
      "npm:rxjs@5.5.0/operator/timeInterval.js",
      "npm:rxjs@5.5.0/add/operator/zipAll.js",
      "npm:rxjs@5.5.0/operator/zipAll.js",
      "npm:rxjs@5.5.0/add/operator/zip.js",
      "npm:rxjs@5.5.0/operator/zip.js",
      "npm:rxjs@5.5.0/add/operator/withLatestFrom.js",
      "npm:rxjs@5.5.0/operator/withLatestFrom.js",
      "npm:rxjs@5.5.0/add/operator/windowWhen.js",
      "npm:rxjs@5.5.0/operator/windowWhen.js",
      "npm:rxjs@5.5.0/add/operator/windowToggle.js",
      "npm:rxjs@5.5.0/operator/windowToggle.js",
      "npm:rxjs@5.5.0/add/operator/windowTime.js",
      "npm:rxjs@5.5.0/operator/windowTime.js",
      "npm:rxjs@5.5.0/add/operator/windowCount.js",
      "npm:rxjs@5.5.0/operator/windowCount.js",
      "npm:rxjs@5.5.0/add/operator/window.js",
      "npm:rxjs@5.5.0/operator/window.js",
      "npm:rxjs@5.5.0/add/operator/toPromise.js",
      "npm:rxjs@5.5.0/add/operator/toArray.js",
      "npm:rxjs@5.5.0/operator/toArray.js",
      "npm:rxjs@5.5.0/add/operator/timestamp.js",
      "npm:rxjs@5.5.0/operator/timestamp.js",
      "npm:rxjs@5.5.0/add/operator/timeoutWith.js",
      "npm:rxjs@5.5.0/operator/timeoutWith.js",
      "npm:rxjs@5.5.0/add/operator/timeout.js",
      "npm:rxjs@5.5.0/operator/timeout.js",
      "npm:rxjs@5.5.0/add/operator/timeInterval.js",
      "npm:rxjs@5.5.0/add/operator/throttleTime.js",
      "npm:rxjs@5.5.0/operator/throttleTime.js",
      "npm:rxjs@5.5.0/add/operator/throttle.js",
      "npm:rxjs@5.5.0/operator/throttle.js",
      "npm:rxjs@5.5.0/add/operator/takeWhile.js",
      "npm:rxjs@5.5.0/operator/takeWhile.js",
      "npm:rxjs@5.5.0/add/operator/takeUntil.js",
      "npm:rxjs@5.5.0/operator/takeUntil.js",
      "npm:rxjs@5.5.0/add/operator/takeLast.js",
      "npm:rxjs@5.5.0/operator/takeLast.js",
      "npm:rxjs@5.5.0/add/operator/take.js",
      "npm:rxjs@5.5.0/operator/take.js",
      "npm:rxjs@5.5.0/add/operator/switchMapTo.js",
      "npm:rxjs@5.5.0/operator/switchMapTo.js",
      "npm:rxjs@5.5.0/add/operator/switchMap.js",
      "npm:rxjs@5.5.0/operator/switchMap.js",
      "npm:rxjs@5.5.0/add/operator/switch.js",
      "npm:rxjs@5.5.0/operator/switch.js",
      "npm:rxjs@5.5.0/add/operator/subscribeOn.js",
      "npm:rxjs@5.5.0/operator/subscribeOn.js",
      "npm:rxjs@5.5.0/operators/subscribeOn.js",
      "npm:rxjs@5.5.0/observable/SubscribeOnObservable.js",
      "npm:rxjs@5.5.0/add/operator/startWith.js",
      "npm:rxjs@5.5.0/operator/startWith.js",
      "npm:rxjs@5.5.0/add/operator/skipWhile.js",
      "npm:rxjs@5.5.0/operator/skipWhile.js",
      "npm:rxjs@5.5.0/add/operator/skipUntil.js",
      "npm:rxjs@5.5.0/operator/skipUntil.js",
      "npm:rxjs@5.5.0/add/operator/skipLast.js",
      "npm:rxjs@5.5.0/operator/skipLast.js",
      "npm:rxjs@5.5.0/add/operator/skip.js",
      "npm:rxjs@5.5.0/operator/skip.js",
      "npm:rxjs@5.5.0/add/operator/single.js",
      "npm:rxjs@5.5.0/operator/single.js",
      "npm:rxjs@5.5.0/add/operator/shareReplay.js",
      "npm:rxjs@5.5.0/operator/shareReplay.js",
      "npm:rxjs@5.5.0/add/operator/share.js",
      "npm:rxjs@5.5.0/operator/share.js",
      "npm:rxjs@5.5.0/add/operator/sequenceEqual.js",
      "npm:rxjs@5.5.0/operator/sequenceEqual.js",
      "npm:rxjs@5.5.0/add/operator/scan.js",
      "npm:rxjs@5.5.0/operator/scan.js",
      "npm:rxjs@5.5.0/add/operator/sampleTime.js",
      "npm:rxjs@5.5.0/operator/sampleTime.js",
      "npm:rxjs@5.5.0/add/operator/sample.js",
      "npm:rxjs@5.5.0/operator/sample.js",
      "npm:rxjs@5.5.0/add/operator/retryWhen.js",
      "npm:rxjs@5.5.0/operator/retryWhen.js",
      "npm:rxjs@5.5.0/add/operator/retry.js",
      "npm:rxjs@5.5.0/operator/retry.js",
      "npm:rxjs@5.5.0/add/operator/repeatWhen.js",
      "npm:rxjs@5.5.0/operator/repeatWhen.js",
      "npm:rxjs@5.5.0/add/operator/repeat.js",
      "npm:rxjs@5.5.0/operator/repeat.js",
      "npm:rxjs@5.5.0/add/operator/reduce.js",
      "npm:rxjs@5.5.0/operator/reduce.js",
      "npm:rxjs@5.5.0/add/operator/race.js",
      "npm:rxjs@5.5.0/operator/race.js",
      "npm:rxjs@5.5.0/add/operator/publishLast.js",
      "npm:rxjs@5.5.0/operator/publishLast.js",
      "npm:rxjs@5.5.0/add/operator/publishReplay.js",
      "npm:rxjs@5.5.0/operator/publishReplay.js",
      "npm:rxjs@5.5.0/add/operator/publishBehavior.js",
      "npm:rxjs@5.5.0/operator/publishBehavior.js",
      "npm:rxjs@5.5.0/add/operator/publish.js",
      "npm:rxjs@5.5.0/operator/publish.js",
      "npm:rxjs@5.5.0/add/operator/pluck.js",
      "npm:rxjs@5.5.0/operator/pluck.js",
      "npm:rxjs@5.5.0/add/operator/partition.js",
      "npm:rxjs@5.5.0/operator/partition.js",
      "npm:rxjs@5.5.0/add/operator/pairwise.js",
      "npm:rxjs@5.5.0/operator/pairwise.js",
      "npm:rxjs@5.5.0/add/operator/onErrorResumeNext.js",
      "npm:rxjs@5.5.0/operator/onErrorResumeNext.js",
      "npm:rxjs@5.5.0/add/operator/observeOn.js",
      "npm:rxjs@5.5.0/operator/observeOn.js",
      "npm:rxjs@5.5.0/add/operator/multicast.js",
      "npm:rxjs@5.5.0/operator/multicast.js",
      "npm:rxjs@5.5.0/add/operator/min.js",
      "npm:rxjs@5.5.0/operator/min.js",
      "npm:rxjs@5.5.0/add/operator/mergeScan.js",
      "npm:rxjs@5.5.0/operator/mergeScan.js",
      "npm:rxjs@5.5.0/add/operator/mergeMapTo.js",
      "npm:rxjs@5.5.0/operator/mergeMapTo.js",
      "npm:rxjs@5.5.0/add/operator/mergeMap.js",
      "npm:rxjs@5.5.0/operator/mergeMap.js",
      "npm:rxjs@5.5.0/add/operator/mergeAll.js",
      "npm:rxjs@5.5.0/operator/mergeAll.js",
      "npm:rxjs@5.5.0/add/operator/merge.js",
      "npm:rxjs@5.5.0/operator/merge.js",
      "npm:rxjs@5.5.0/add/operator/max.js",
      "npm:rxjs@5.5.0/operator/max.js",
      "npm:rxjs@5.5.0/add/operator/materialize.js",
      "npm:rxjs@5.5.0/operator/materialize.js",
      "npm:rxjs@5.5.0/add/operator/mapTo.js",
      "npm:rxjs@5.5.0/operator/mapTo.js",
      "npm:rxjs@5.5.0/add/operator/map.js",
      "npm:rxjs@5.5.0/operator/map.js",
      "npm:rxjs@5.5.0/add/operator/every.js",
      "npm:rxjs@5.5.0/operator/every.js",
      "npm:rxjs@5.5.0/add/operator/let.js",
      "npm:rxjs@5.5.0/operator/let.js",
      "npm:rxjs@5.5.0/add/operator/last.js",
      "npm:rxjs@5.5.0/operator/last.js",
      "npm:rxjs@5.5.0/add/operator/auditTime.js",
      "npm:rxjs@5.5.0/operator/auditTime.js",
      "npm:rxjs@5.5.0/add/operator/audit.js",
      "npm:rxjs@5.5.0/operator/audit.js",
      "npm:rxjs@5.5.0/add/operator/isEmpty.js",
      "npm:rxjs@5.5.0/operator/isEmpty.js",
      "npm:rxjs@5.5.0/add/operator/ignoreElements.js",
      "npm:rxjs@5.5.0/operator/ignoreElements.js",
      "npm:rxjs@5.5.0/add/operator/groupBy.js",
      "npm:rxjs@5.5.0/operator/groupBy.js",
      "npm:rxjs@5.5.0/add/operator/first.js",
      "npm:rxjs@5.5.0/operator/first.js",
      "npm:rxjs@5.5.0/add/operator/findIndex.js",
      "npm:rxjs@5.5.0/operator/findIndex.js",
      "npm:rxjs@5.5.0/add/operator/find.js",
      "npm:rxjs@5.5.0/operator/find.js",
      "npm:rxjs@5.5.0/add/operator/finally.js",
      "npm:rxjs@5.5.0/operator/finally.js",
      "npm:rxjs@5.5.0/add/operator/filter.js",
      "npm:rxjs@5.5.0/operator/filter.js",
      "npm:rxjs@5.5.0/add/operator/elementAt.js",
      "npm:rxjs@5.5.0/operator/elementAt.js",
      "npm:rxjs@5.5.0/add/operator/expand.js",
      "npm:rxjs@5.5.0/operator/expand.js",
      "npm:rxjs@5.5.0/add/operator/exhaustMap.js",
      "npm:rxjs@5.5.0/operator/exhaustMap.js",
      "npm:rxjs@5.5.0/add/operator/exhaust.js",
      "npm:rxjs@5.5.0/operator/exhaust.js",
      "npm:rxjs@5.5.0/add/operator/do.js",
      "npm:rxjs@5.5.0/operator/do.js",
      "npm:rxjs@5.5.0/add/operator/distinctUntilKeyChanged.js",
      "npm:rxjs@5.5.0/operator/distinctUntilKeyChanged.js",
      "npm:rxjs@5.5.0/add/operator/distinctUntilChanged.js",
      "npm:rxjs@5.5.0/operator/distinctUntilChanged.js",
      "npm:rxjs@5.5.0/add/operator/distinct.js",
      "npm:rxjs@5.5.0/operator/distinct.js",
      "npm:rxjs@5.5.0/add/operator/delayWhen.js",
      "npm:rxjs@5.5.0/operator/delayWhen.js",
      "npm:rxjs@5.5.0/add/operator/delay.js",
      "npm:rxjs@5.5.0/operator/delay.js",
      "npm:rxjs@5.5.0/add/operator/defaultIfEmpty.js",
      "npm:rxjs@5.5.0/operator/defaultIfEmpty.js",
      "npm:rxjs@5.5.0/add/operator/debounceTime.js",
      "npm:rxjs@5.5.0/operator/debounceTime.js",
      "npm:rxjs@5.5.0/add/operator/debounce.js",
      "npm:rxjs@5.5.0/operator/debounce.js",
      "npm:rxjs@5.5.0/add/operator/dematerialize.js",
      "npm:rxjs@5.5.0/operator/dematerialize.js",
      "npm:rxjs@5.5.0/add/operator/count.js",
      "npm:rxjs@5.5.0/operator/count.js",
      "npm:rxjs@5.5.0/add/operator/concatMapTo.js",
      "npm:rxjs@5.5.0/operator/concatMapTo.js",
      "npm:rxjs@5.5.0/add/operator/concatMap.js",
      "npm:rxjs@5.5.0/operator/concatMap.js",
      "npm:rxjs@5.5.0/add/operator/concatAll.js",
      "npm:rxjs@5.5.0/operator/concatAll.js",
      "npm:rxjs@5.5.0/add/operator/concat.js",
      "npm:rxjs@5.5.0/operator/concat.js",
      "npm:rxjs@5.5.0/add/operator/combineLatest.js",
      "npm:rxjs@5.5.0/operator/combineLatest.js",
      "npm:rxjs@5.5.0/add/operator/combineAll.js",
      "npm:rxjs@5.5.0/operator/combineAll.js",
      "npm:rxjs@5.5.0/add/operator/catch.js",
      "npm:rxjs@5.5.0/operator/catch.js",
      "npm:rxjs@5.5.0/add/operator/bufferWhen.js",
      "npm:rxjs@5.5.0/operator/bufferWhen.js",
      "npm:rxjs@5.5.0/add/operator/bufferToggle.js",
      "npm:rxjs@5.5.0/operator/bufferToggle.js",
      "npm:rxjs@5.5.0/add/operator/bufferTime.js",
      "npm:rxjs@5.5.0/operator/bufferTime.js",
      "npm:rxjs@5.5.0/add/operator/bufferCount.js",
      "npm:rxjs@5.5.0/operator/bufferCount.js",
      "npm:rxjs@5.5.0/add/operator/buffer.js",
      "npm:rxjs@5.5.0/operator/buffer.js",
      "npm:rxjs@5.5.0/add/observable/dom/webSocket.js",
      "npm:rxjs@5.5.0/observable/dom/webSocket.js",
      "npm:rxjs@5.5.0/observable/dom/WebSocketSubject.js",
      "npm:rxjs@5.5.0/util/assign.js",
      "npm:rxjs@5.5.0/add/observable/dom/ajax.js",
      "npm:rxjs@5.5.0/observable/dom/ajax.js",
      "npm:rxjs@5.5.0/add/observable/zip.js",
      "npm:rxjs@5.5.0/observable/zip.js",
      "npm:rxjs@5.5.0/add/observable/timer.js",
      "npm:rxjs@5.5.0/add/observable/throw.js",
      "npm:rxjs@5.5.0/observable/throw.js",
      "npm:rxjs@5.5.0/observable/ErrorObservable.js",
      "npm:rxjs@5.5.0/add/observable/using.js",
      "npm:rxjs@5.5.0/observable/using.js",
      "npm:rxjs@5.5.0/observable/UsingObservable.js",
      "npm:rxjs@5.5.0/add/observable/range.js",
      "npm:rxjs@5.5.0/observable/range.js",
      "npm:rxjs@5.5.0/observable/RangeObservable.js",
      "npm:rxjs@5.5.0/add/observable/pairs.js",
      "npm:rxjs@5.5.0/observable/pairs.js",
      "npm:rxjs@5.5.0/observable/PairsObservable.js",
      "npm:rxjs@5.5.0/add/observable/onErrorResumeNext.js",
      "npm:rxjs@5.5.0/observable/onErrorResumeNext.js",
      "npm:rxjs@5.5.0/add/observable/of.js",
      "npm:rxjs@5.5.0/add/observable/never.js",
      "npm:rxjs@5.5.0/observable/never.js",
      "npm:rxjs@5.5.0/observable/NeverObservable.js",
      "npm:rxjs@5.5.0/add/observable/race.js",
      "npm:rxjs@5.5.0/add/observable/merge.js",
      "npm:rxjs@5.5.0/observable/merge.js",
      "npm:rxjs@5.5.0/add/observable/interval.js",
      "npm:rxjs@5.5.0/observable/interval.js",
      "npm:rxjs@5.5.0/observable/IntervalObservable.js",
      "npm:rxjs@5.5.0/add/observable/if.js",
      "npm:rxjs@5.5.0/observable/if.js",
      "npm:rxjs@5.5.0/observable/IfObservable.js",
      "npm:rxjs@5.5.0/add/observable/generate.js",
      "npm:rxjs@5.5.0/observable/generate.js",
      "npm:rxjs@5.5.0/observable/GenerateObservable.js",
      "npm:rxjs@5.5.0/add/observable/fromPromise.js",
      "npm:rxjs@5.5.0/observable/fromPromise.js",
      "npm:rxjs@5.5.0/add/observable/fromEventPattern.js",
      "npm:rxjs@5.5.0/observable/fromEventPattern.js",
      "npm:rxjs@5.5.0/observable/FromEventPatternObservable.js",
      "npm:rxjs@5.5.0/add/observable/fromEvent.js",
      "npm:rxjs@5.5.0/observable/fromEvent.js",
      "npm:rxjs@5.5.0/observable/FromEventObservable.js",
      "npm:rxjs@5.5.0/add/observable/from.js",
      "npm:rxjs@5.5.0/add/observable/forkJoin.js",
      "npm:rxjs@5.5.0/observable/forkJoin.js",
      "npm:rxjs@5.5.0/observable/ForkJoinObservable.js",
      "npm:rxjs@5.5.0/add/observable/empty.js",
      "npm:rxjs@5.5.0/observable/empty.js",
      "npm:rxjs@5.5.0/add/observable/defer.js",
      "npm:rxjs@5.5.0/observable/defer.js",
      "npm:rxjs@5.5.0/observable/DeferObservable.js",
      "npm:rxjs@5.5.0/add/observable/concat.js",
      "npm:rxjs@5.5.0/add/observable/combineLatest.js",
      "npm:rxjs@5.5.0/observable/combineLatest.js",
      "npm:rxjs@5.5.0/add/observable/bindNodeCallback.js",
      "npm:rxjs@5.5.0/observable/bindNodeCallback.js",
      "npm:rxjs@5.5.0/observable/BoundNodeCallbackObservable.js",
      "npm:rxjs@5.5.0/add/observable/bindCallback.js",
      "npm:rxjs@5.5.0/observable/bindCallback.js",
      "npm:rxjs@5.5.0/observable/BoundCallbackObservable.js"
    ]
  },

  packages: {
    "app": {
      "main": "./main.ts",
      "defaultExtension": "ts"
    }
  },

  map: {
    "@angular/animations": "node_modules/@angular/animations/bundles/animations.umd.js",
    "@angular/animations/browser": "node_modules/@angular/animations/bundles/animations-browser.umd.js",
    "@angular/cdk": "node_modules/@angular/cdk/bundles/cdk.umd.js",
    "@angular/cdk/a11y": "node_modules/@angular/cdk/bundles/cdk-a11y.umd.js",
    "@angular/cdk/bidi": "node_modules/@angular/cdk/bundles/cdk-bidi.umd.js",
    "@angular/cdk/coercion": "node_modules/@angular/cdk/bundles/cdk-coercion.umd.js",
    "@angular/cdk/collections": "node_modules/@angular/cdk/bundles/cdk-collections.umd.js",
    "@angular/cdk/keycodes": "node_modules/@angular/cdk/bundles/cdk-keycodes.umd.js",
    "@angular/cdk/observers": "node_modules/@angular/cdk/bundles/cdk-observers.umd.js",
    "@angular/cdk/overlay": "node_modules/@angular/cdk/bundles/cdk-overlay.umd.js",
    "@angular/cdk/platform": "node_modules/@angular/cdk/bundles/cdk-platform.umd.js",
    "@angular/cdk/portal": "node_modules/@angular/cdk/bundles/cdk-portal.umd.js",
    "@angular/cdk/rxjs": "node_modules/@angular/cdk/bundles/cdk-rxjs.umd.js",
    "@angular/cdk/scrolling": "node_modules/@angular/cdk/bundles/cdk-scrolling.umd.js",
    "@angular/cdk/stepper": "node_modules/@angular/cdk/bundles/cdk-stepper.umd.js",
    "@angular/cdk/table": "node_modules/@angular/cdk/bundles/cdk-table.umd.js",
    "@angular/common": "node_modules/@angular/common/bundles/common.umd.js",
    "@angular/compiler": "node_modules/@angular/compiler/bundles/compiler.umd.js",
    "@angular/core": "node_modules/@angular/core/bundles/core.umd.js",
    "@angular/forms": "node_modules/@angular/forms/bundles/forms.umd.js",
    "@angular/http": "node_modules/@angular/http/bundles/http.umd.js",
    "@angular/material": "node_modules/@angular/material/bundles/material.umd.js",
    "@angular/platform-browser": "node_modules/@angular/platform-browser/bundles/platform-browser.umd.js",
    "@angular/platform-browser-dynamic": "node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js",
    "@angular/platform-browser/animations": "node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js",
    "@angular/router": "node_modules/@angular/router/bundles/router.umd.js",
    "hammerjs": "node_modules/hammerjs/hammer.min",
    "reflect-metadata": "node_modules/reflect-metadata/Reflect.js",
    "rxjs": "npm:rxjs@5.5.0",
    "typescript": "npm:typescript@2.5.3",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.1": {
      "buffer": "npm:buffer@5.0.8"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.1"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.3",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-net@0.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "timers": "github:jspm/nodelibs-timers@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.10"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-timers@0.1.0": {
      "timers-browserify": "npm:timers-browserify@1.4.2"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:asn1.js@4.9.1": {
      "bn.js": "npm:bn.js@4.11.8",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "inherits": "npm:inherits@2.0.3",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:browserify-aes@1.0.8": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.4",
      "create-hash": "npm:create-hash@1.1.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.3",
      "inherits": "npm:inherits@2.0.3",
      "safe-buffer": "npm:safe-buffer@5.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.8",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.3"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "cipher-base": "npm:cipher-base@1.0.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.8",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.5",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-sign@4.0.4": {
      "bn.js": "npm:bn.js@4.11.8",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.3",
      "create-hmac": "npm:create-hmac@1.1.6",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.4.0",
      "inherits": "npm:inherits@2.0.3",
      "parse-asn1": "npm:parse-asn1@5.1.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer@5.0.8": {
      "base64-js": "npm:base64-js@1.2.1",
      "ieee754": "npm:ieee754@1.1.8",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:cipher-base@1.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "inherits": "npm:inherits@2.0.3",
      "safe-buffer": "npm:safe-buffer@5.1.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.8",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.4.0"
    },
    "npm:create-hash@1.1.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "cipher-base": "npm:cipher-base@1.0.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.3",
      "ripemd160": "npm:ripemd160@2.0.1",
      "sha.js": "npm:sha.js@2.4.9"
    },
    "npm:create-hmac@1.1.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "cipher-base": "npm:cipher-base@1.0.4",
      "create-hash": "npm:create-hash@1.1.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.3",
      "ripemd160": "npm:ripemd160@2.0.1",
      "safe-buffer": "npm:safe-buffer@5.1.1",
      "sha.js": "npm:sha.js@2.4.9"
    },
    "npm:crypto-browserify@3.11.1": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.4",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.3",
      "create-hmac": "npm:create-hmac@1.1.6",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.3",
      "pbkdf2": "npm:pbkdf2@3.0.14",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.5",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "inherits": "npm:inherits@2.0.3",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.8",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.1",
      "randombytes": "npm:randombytes@2.0.5",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:elliptic@6.4.0": {
      "bn.js": "npm:bn.js@4.11.8",
      "brorand": "npm:brorand@1.1.0",
      "hash.js": "npm:hash.js@1.1.3",
      "hmac-drbg": "npm:hmac-drbg@1.0.1",
      "inherits": "npm:inherits@2.0.3",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "minimalistic-crypto-utils": "npm:minimalistic-crypto-utils@1.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:evp_bytestokey@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "md5.js": "npm:md5.js@1.3.4",
      "safe-buffer": "npm:safe-buffer@5.1.1"
    },
    "npm:hash-base@2.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "inherits": "npm:inherits@2.0.3",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:hash-base@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "inherits": "npm:inherits@2.0.3",
      "safe-buffer": "npm:safe-buffer@5.1.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:hash.js@1.1.3": {
      "inherits": "npm:inherits@2.0.3",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:hmac-drbg@1.0.1": {
      "hash.js": "npm:hash.js@1.1.3",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "minimalistic-crypto-utils": "npm:minimalistic-crypto-utils@1.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:inherits@2.0.3": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:md5.js@1.3.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "hash-base": "npm:hash-base@3.0.4",
      "inherits": "npm:inherits@2.0.3"
    },
    "npm:miller-rabin@4.0.1": {
      "bn.js": "npm:bn.js@4.11.8",
      "brorand": "npm:brorand@1.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:parse-asn1@5.1.0": {
      "asn1.js": "npm:asn1.js@4.9.1",
      "browserify-aes": "npm:browserify-aes@1.0.8",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.3",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.3",
      "pbkdf2": "npm:pbkdf2@3.0.14",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.3",
      "create-hmac": "npm:create-hmac@1.1.6",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "ripemd160": "npm:ripemd160@2.0.1",
      "safe-buffer": "npm:safe-buffer@5.1.1",
      "sha.js": "npm:sha.js@2.4.9"
    },
    "npm:process@0.11.10": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.8",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.1.0",
      "randombytes": "npm:randombytes@2.0.5"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:randombytes@2.0.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "safe-buffer": "npm:safe-buffer@5.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.3",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:ripemd160@2.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "hash-base": "npm:hash-base@2.0.2",
      "inherits": "npm:inherits@2.0.3"
    },
    "npm:rxjs@5.5.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "symbol-observable": "npm:symbol-observable@1.0.4"
    },
    "npm:safe-buffer@5.1.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:sha.js@2.4.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "safe-buffer": "npm:safe-buffer@5.1.1"
    },
    "npm:source-map-support@0.5.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.6.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:source-map@0.6.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.3",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1"
    },
    "npm:timers-browserify@1.4.2": {
      "process": "npm:process@0.11.10"
    },
    "npm:typescript@2.5.3": {
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "source-map-support": "npm:source-map-support@0.5.0"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  }
});
